insert into public.opportunity_sources
(name, base_url, source_domain, category, trust_level, active)
values
('Google Summer of Code', 'https://summerofcode.withgoogle.com', 'summerofcode.withgoogle.com', 'Open Source', 95, true),
('Devpost', 'https://devpost.com', 'devpost.com', 'Hackathons', 90, true),
('MLH', 'https://mlh.io', 'mlh.io', 'Hackathons', 90, true),
('National Scholarship Portal', 'https://scholarships.gov.in', 'scholarships.gov.in', 'Scholarships', 95, true),
('AICTE', 'https://www.aicte-india.org', 'aicte-india.org', 'Internships', 90, true),
('Startup India', 'https://www.startupindia.gov.in', 'startupindia.gov.in', 'Startup Programs', 90, true),
('MyGov', 'https://www.mygov.in', 'mygov.in', 'Government Benefits', 90, true),
('DAAD', 'https://www.daad.de', 'daad.de', 'Scholarships', 95, true),
('MITACS', 'https://www.mitacs.ca', 'mitacs.ca', 'Research', 95, true),
('Fulbright', 'https://foreign.fulbrightonline.org', 'foreign.fulbrightonline.org', 'Fellowships', 95, true),
('Chevening', 'https://www.chevening.org', 'chevening.org', 'Scholarships', 95, true),
('Erasmus Mundus', 'https://erasmus-plus.ec.europa.eu', 'erasmus-plus.ec.europa.eu', 'Scholarships', 95, true),
('GitHub Campus Experts', 'https://education.github.com', 'education.github.com', 'Open Source', 90, true),
('Microsoft Learn Student Ambassadors', 'https://studentambassadors.microsoft.com', 'studentambassadors.microsoft.com', 'Student Programs', 90, true),
('Y Combinator Startup School', 'https://www.startupschool.org', 'startupschool.org', 'Startup Programs', 90, true);

insert into public.opportunities
(
  title,
  provider,
  category,
  country,
  states,
  eligible_roles,
  eligible_education,
  eligible_fields,
  eligible_years,
  eligible_gender,
  eligible_category,
  eligible_income_range,
  skills,
  interests,
  deadline,
  status,
  official_url,
  source_domain,
  trust_score,
  verification_status,
  verification_notes,
  description,
  benefits,
  documents_required
)
values
(
  'Google Summer of Code',
  'Google',
  'Open Source',
  'Global',
  null,
  array['Student', 'Developer']::text[],
  array['Undergraduate', 'Postgraduate', 'Graduate', 'Other']::text[],
  array['Computer Science', 'AI', 'Engineering', 'Other']::text[],
  null,
  null,
  null,
  null,
  array['Open Source', 'Python', 'React', 'Full Stack', 'AI']::text[],
  array['Open Source', 'Global Opportunities']::text[],
  'Check official source',
  'active',
  'https://summerofcode.withgoogle.com',
  'summerofcode.withgoogle.com',
  96,
  'verified',
  array['Official Google Summer of Code website.', 'Globally recognized open-source program.']::text[],
  'A global program connecting new open-source contributors with mentoring organizations.',
  array['Mentorship', 'Open-source contribution experience', 'Stipend where applicable']::text[],
  array['Application proposal', 'Contributor profile']::text[]
),
(
  'MLH Hackathons',
  'Major League Hacking',
  'Hackathons',
  'Global',
  null,
  array['Student', 'Developer']::text[],
  array['School', 'Undergraduate', 'Postgraduate', 'Graduate', 'Other']::text[],
  array['Computer Science', 'Engineering', 'Design', 'Business', 'Other']::text[],
  null,
  null,
  null,
  null,
  array['React', 'Python', 'AI', 'Design', 'Full Stack']::text[],
  array['Hackathons', 'Competitions', 'Global Opportunities']::text[],
  'Ongoing',
  'active',
  'https://mlh.io/seasons',
  'mlh.io',
  92,
  'verified',
  array['Official MLH events page.', 'Known international hackathon organizer.']::text[],
  'A collection of student-focused hackathons and technology events.',
  array['Hackathon participation', 'Networking', 'Prizes where applicable']::text[],
  array['Student information', 'Team details where required']::text[]
),
(
  'Devpost Hackathons',
  'Devpost',
  'Hackathons',
  'Global',
  null,
  array['Student', 'Developer', 'Founder', 'Professional']::text[],
  null,
  null,
  null,
  null,
  null,
  null,
  array['AI', 'React', 'React Native', 'Python', 'Design', 'Business']::text[],
  array['Hackathons', 'Competitions', 'Startup Programs']::text[],
  'Ongoing',
  'active',
  'https://devpost.com/hackathons',
  'devpost.com',
  90,
  'verified',
  array['Official Devpost hackathon directory.', 'Widely used competition platform.']::text[],
  'A platform listing online and in-person hackathons from verified hosts.',
  array['Competitions', 'Prizes', 'Portfolio projects']::text[],
  array['Devpost profile', 'Project submission']::text[]
),
(
  'National Scholarship Portal Scholarships',
  'Government of India',
  'Scholarships',
  'India',
  null,
  array['Student']::text[],
  array['School', 'Intermediate', 'Diploma', 'Undergraduate', 'Postgraduate']::text[],
  null,
  null,
  null,
  null,
  null,
  array[]::text[],
  array['Scholarships', 'Government Benefits']::text[],
  'Check official source',
  'active',
  'https://scholarships.gov.in',
  'scholarships.gov.in',
  96,
  'verified',
  array['Official Government of India scholarship portal.']::text[],
  'Government-backed scholarship schemes for eligible Indian students.',
  array['Scholarship funding', 'Access to central and state schemes']::text[],
  array['Identity proof', 'Academic records', 'Bank details', 'Income/category certificate if applicable']::text[]
),
(
  'AICTE Internship Portal',
  'AICTE',
  'Internships',
  'India',
  null,
  array['Student']::text[],
  array['Diploma', 'Undergraduate', 'Postgraduate']::text[],
  array['Engineering', 'Computer Science', 'Business', 'Design', 'Other']::text[],
  null,
  null,
  null,
  null,
  array['Python', 'React', 'AI', 'Data Science', 'Cloud']::text[],
  array['Internships', 'Government Benefits']::text[],
  'Ongoing',
  'active',
  'https://internship.aicte-india.org',
  'internship.aicte-india.org',
  91,
  'verified',
  array['Official AICTE internship portal.']::text[],
  'Internship discovery portal for students in India.',
  array['Internship opportunities', 'Industry exposure']::text[],
  array['Student details', 'Academic details', 'Resume where required']::text[]
);